mysql:
  host: "127.0.0.1"
  user: "root"
  password: ""
  database: "my_server"

players:
  enabled: false
  table: "players"

ranks:
  enabled: false
  table: "players"
  groups:
    2: "admin"
    1: "moderator"

online-players:
  enabled: false
  table: "online_players"
  update-interval: 5

events:
  enabled: false
  table: "player_events"

online-time:
  enabled: false
  table: "online_time"

contributors:
  enabled: false
  table: "contributors"
  # TODO

commands-filter:
  enabled: false
  allowed-commands:
    - "home"
    - "sethome"
    - "spawn"
  not-allowed-message: "Unknown command: /{COMMAND}"
